name: ScriptRunner

on:
  schedule:
    - cron: '0 12 * * *' # runs at 12:00 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # install the python version needed
        
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      
      #- name: install python packages
      #  run: |
       #   python -m pip install --upgrade pip
        #  pip install -r requirements.txt
          
      - name: execute py script # run sj-gobierno.py to get the latest data
        run: python espnexporter.py
      
      - name: Git commit
        run: |
          git add data
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Commiting data" 
       
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main 
          
      #- name: Git push
       # run: |
        #  git push "https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main
        #env:
         # TOKEN: ${{ secrets.GITHUB_TOKEN }}
